/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Patient;

import business.EcoSystem;
import business.Enterprise.SiteEnterprise;
import business.Organization.PatientOrganization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.PHD.ManagePHDUserAccountJPanel;

/**
 *
 * @author Abhishek
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    
            
    public PatientWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        managePersonelDetailsJButton = new javax.swing.JButton();
        manageMedicalHistoryJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel1.setText("Patient Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        managePersonelDetailsJButton.setText("Manage Personel Details");
        managePersonelDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonelDetailsJButtonActionPerformed(evt);
            }
        });
        add(managePersonelDetailsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        manageMedicalHistoryJButton.setText("Manage Medical History");
        manageMedicalHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMedicalHistoryJButtonActionPerformed(evt);
            }
        });
        add(manageMedicalHistoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 173, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void managePersonelDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonelDetailsJButtonActionPerformed
         // TODO add your handling code here:
          ManagePersonelDetailsJPanel mpdjp = new ManagePersonelDetailsJPanel(userProcessContainer,userAccount);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManagePersonelDetailsJPanel", mpdjp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePersonelDetailsJButtonActionPerformed

    private void manageMedicalHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMedicalHistoryJButtonActionPerformed
        // TODO add your handling code here:
        // ManageMedicalHistoryJPanel mmhjp = new ManageMedicalHistoryJPanel(userProcessContainer,userAccount);
       // CardLayout layout = (CardLayout) userProcessContainer.getLayout();
      //  userProcessContainer.add("ManageMedicalHistoryJPanel", mmhjp);
    //  layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMedicalHistoryJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageMedicalHistoryJButton;
    private javax.swing.JButton managePersonelDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
