/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Patient;

/**
 *
 * @author Abhishek
 */
public class ReportAllergyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportAllergyJPanel
     */
    public ReportAllergyJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reportJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sideEffectsJTextArea = new javax.swing.JTextArea();
        vaccineNameJTextField = new javax.swing.JTextField();
        vaccineTypeJTextField = new javax.swing.JTextField();
        batchNoJTextField = new javax.swing.JTextField();
        dateAdminsteredJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel1.setText("Report an Allergy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel2.setText("Vaccine Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 113, -1, -1));

        jLabel3.setText("Vaccine Type :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 159, -1, -1));

        jLabel4.setText("Date Administered :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 234, -1, -1));

        reportJButton.setText("Report");
        add(reportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        backJButton.setText("<< Back");
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel5.setText("Side Effects :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 271, -1, -1));

        jLabel6.setText("Batch Number :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 194, -1, -1));

        sideEffectsJTextArea.setColumns(20);
        sideEffectsJTextArea.setRows(5);
        jScrollPane1.setViewportView(sideEffectsJTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 271, 203, 78));

        vaccineNameJTextField.setEditable(false);
        add(vaccineNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 110, 193, -1));

        vaccineTypeJTextField.setEditable(false);
        add(vaccineTypeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 156, 193, -1));

        batchNoJTextField.setEditable(false);
        add(batchNoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 191, 193, -1));

        dateAdminsteredJTextField.setEditable(false);
        add(dateAdminsteredJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 231, 193, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField batchNoJTextField;
    private javax.swing.JTextField dateAdminsteredJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reportJButton;
    private javax.swing.JTextArea sideEffectsJTextArea;
    private javax.swing.JTextField vaccineNameJTextField;
    private javax.swing.JTextField vaccineTypeJTextField;
    // End of variables declaration//GEN-END:variables
}
