/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Sites;

import business.Doctor.Doctor;
import business.Organization.DoctorOrganization;
import business.Person.Person;
import business.Role.DoctorRole;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class AddDoctorDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDoctorDetailsJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DoctorOrganization doctorOrganization;
    public AddDoctorDetailsJPanel(JPanel userProcessContainer,DoctorOrganization doctorOrganization,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.doctorOrganization = doctorOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        specializationJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        addDoctorJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Add Doctor Specialization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 13, -1, -1));

        jLabel2.setText("Specialization :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 107, -1, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 104, 121, 16));
        add(specializationJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 104, 183, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 13, -1, -1));

        addDoctorJButton.setText("Add Doctor");
        addDoctorJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorJButtonActionPerformed(evt);
            }
        });
        add(addDoctorJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
         if(userProcessContainer.getComponent(userProcessContainer.getComponentCount()-1) instanceof ManageSiteUserAccountJPanel)
        {
            ManageSiteUserAccountJPanel msuajp = (ManageSiteUserAccountJPanel)userProcessContainer.getComponent(userProcessContainer.getComponentCount()-1);
            msuajp.populateTable();
            
        }

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addDoctorJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorJButtonActionPerformed
        // TODO add your handling code here:
        String specialization  = specializationJTextField.getText().trim();
        if(specialization.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Enter doctor specialization");
            return;
        }
        
        Person person =  userAccount.getPerson();
        
        person.setQualification(specialization);
        UserAccount ua = doctorOrganization.getUserAccountDirectory().createUserAccount(userAccount.getUserName(), userAccount.getPassword(), userAccount.getPerson(),new DoctorRole());
        ua.setStatus(userAccount.getStatus());
        ua.setPerson(person);
        specializationJTextField.setText("");
        
        userProcessContainer.remove(this);
        
         if(userProcessContainer.getComponent(userProcessContainer.getComponentCount()-1) instanceof ManageSiteUserAccountJPanel)
        {
            ManageSiteUserAccountJPanel msuajp = (ManageSiteUserAccountJPanel)userProcessContainer.getComponent(userProcessContainer.getComponentCount()-1);
            msuajp.populateTable();
            
        }

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_addDoctorJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctorJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField specializationJTextField;
    // End of variables declaration//GEN-END:variables
}
