/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Sites;

import userInterface.Distributor.ManageDistributorPersonJPanel;
import business.EcoSystem;
import business.Enterprise.SiteEnterprise;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class HospitalWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    private SiteEnterprise siteEnterprise;
    
    public HospitalWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecoSystem, SiteEnterprise siteEnterprise,UserAccount userAccount ) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.siteEnterprise = siteEnterprise;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePatientsJButton = new javax.swing.JButton();
        manageOrdersJButton = new javax.swing.JButton();
        manageDoctorJButton = new javax.swing.JButton();
        manageInventoryJButton = new javax.swing.JButton();
        managePaymentJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        manageSiteUserAccountJButton = new javax.swing.JButton();
        managePersonJButton = new javax.swing.JButton();
        orderHistoryJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managePatientsJButton.setText("Manage Patients");
        managePatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePatientsJButtonActionPerformed(evt);
            }
        });
        add(managePatientsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 161, 30));

        manageOrdersJButton.setText("Manage Orders");
        manageOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersJButtonActionPerformed(evt);
            }
        });
        add(manageOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 161, 40));

        manageDoctorJButton.setText("Manage Doctors");
        manageDoctorJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDoctorJButtonActionPerformed(evt);
            }
        });
        add(manageDoctorJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 161, 40));

        manageInventoryJButton.setText("Manage Inventory");
        manageInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInventoryJButtonActionPerformed(evt);
            }
        });
        add(manageInventoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 161, 40));

        managePaymentJButton.setText("Manage Payments");
        managePaymentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePaymentJButtonActionPerformed(evt);
            }
        });
        add(managePaymentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 161, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel1.setText("Hospital Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 30));

        manageSiteUserAccountJButton.setText("Manage User Account");
        manageSiteUserAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSiteUserAccountJButtonActionPerformed(evt);
            }
        });
        add(manageSiteUserAccountJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 161, 30));

        managePersonJButton.setText("Manage Person ");
        managePersonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonJButtonActionPerformed(evt);
            }
        });
        add(managePersonJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 161, 30));

        orderHistoryJButton.setText("View Order History");
        orderHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderHistoryJButtonActionPerformed(evt);
            }
        });
        add(orderHistoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void managePaymentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePaymentJButtonActionPerformed
        // TODO add your handling code here:
        ManageSitePaymentAccountsJPanel msajp = new ManageSitePaymentAccountsJPanel(userProcessContainer, siteEnterprise, userAccount , ecoSystem);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageSiteAccountsJPanel", msajp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePaymentJButtonActionPerformed

    private void managePersonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonJButtonActionPerformed
        // TODO add your handling code here:
        ManageSitePersonJPanel mpjp = new ManageSitePersonJPanel(userProcessContainer, siteEnterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManagePersonJPanel",mpjp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePersonJButtonActionPerformed

    private void manageSiteUserAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSiteUserAccountJButtonActionPerformed
        // TODO add your handling code here:
        
        ManageSiteUserAccountJPanel msuajp = new ManageSiteUserAccountJPanel(userProcessContainer, siteEnterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageSiteUserAccountJPanel",msuajp);
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageSiteUserAccountJButtonActionPerformed

    private void managePatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientsJButtonActionPerformed
        // TODO add your handling code here:
        ManagePatientJPanel mpjp = new ManagePatientJPanel(userProcessContainer, siteEnterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManagePatientJPanel",mpjp);
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_managePatientsJButtonActionPerformed

    private void manageDoctorJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDoctorJButtonActionPerformed
        // TODO add your handling code here:
        ManageDoctorJPanel mdjp = new ManageDoctorJPanel(userProcessContainer, siteEnterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageSiteUserAccountJPanel",mdjp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDoctorJButtonActionPerformed

    private void manageOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersJButtonActionPerformed
        // TODO add your handling code here:
        ManageSiteOrdersJPanel msop = new ManageSiteOrdersJPanel(userProcessContainer,ecoSystem,userAccount,siteEnterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageSiteOrdersPanel",msop);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrdersJButtonActionPerformed

    private void manageInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInventoryJButtonActionPerformed
        // TODO add your handling code here:
        ManageSiteInventoryJPanel msijp = new ManageSiteInventoryJPanel(userProcessContainer,siteEnterprise);
          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageSiteInventoryJPanel",msijp);
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageInventoryJButtonActionPerformed

    private void orderHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderHistoryJButtonActionPerformed
        // TODO add your handling code here:
         ViewSiteOrderHistoryJPanel vsohjp = new ViewSiteOrderHistoryJPanel(userProcessContainer,userAccount);
          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ViewSiteOrderHistoryJPanel",vsohjp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderHistoryJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageDoctorJButton;
    private javax.swing.JButton manageInventoryJButton;
    private javax.swing.JButton manageOrdersJButton;
    private javax.swing.JButton managePatientsJButton;
    private javax.swing.JButton managePaymentJButton;
    private javax.swing.JButton managePersonJButton;
    private javax.swing.JButton manageSiteUserAccountJButton;
    private javax.swing.JButton orderHistoryJButton;
    // End of variables declaration//GEN-END:variables
}
