/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Sites;

import business.Doctor.Doctor;
import business.Enterprise.SiteEnterprise;
import business.Organization.DoctorOrganization;
import business.Organization.Organization;
import business.Patient.EncounterDirectory;
import business.Person.Person;
import business.Person.PersonDirectory;
import business.Role.Role;
import business.UserAccount.UserAccount;
import business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDoctorJPanel
     */
    private JPanel userProcessContainer;
    private SiteEnterprise siteEnterprise;
    private UserAccountDirectory userAccountDirectory;
    private EncounterDirectory encounterDirectory;
    private DoctorOrganization doctorOrganization;
    
    public ManageDoctorJPanel(JPanel userProcessContainer,SiteEnterprise siteEnterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.siteEnterprise = siteEnterprise;
        this.userAccountDirectory = siteEnterprise.getUserAccountDirectory();
        this.encounterDirectory = siteEnterprise.getEncounterDirectory();
        
        
        for(Organization o : siteEnterprise.getOrganizationDirectory().getOrganizationList()){
            if(o instanceof DoctorOrganization){
                doctorOrganization = (DoctorOrganization)o;
            }
        }
        
        this.userAccountDirectory = doctorOrganization.getUserAccountDirectory();
        populateDoctorTable();
    }

    private void populateDoctorTable()
    {
    
        DefaultTableModel model = (DefaultTableModel) doctorJTable.getModel();
        model.setRowCount(0);
        
         for(UserAccount ua : userAccountDirectory.getUserAccountList()){
            if(ua.getRole().getRoleName().equals(Role.RoleType.DoctorRole.getValue())){
                Object[] row = new Object[5];
                Person p = ua.getPerson();
                row[0] = ua.getPerson().getSsn();
                row[1] = ua.getPerson().getFirstName();
                row[2] = ua.getPerson().getLastName();
                row[3] = p.getAddress().getStreetName()+ " " + p.getAddress().getCity() + " " + p.getAddress().getState() + " " + p.getAddress().getZipcode();
                row[4] = ua;
                model.addRow(row);
            } 
        }
        
        /*
        for(UserAccount ua : userAccountDirectory.getUserAccountList())
        {
            for(Organization o : siteEnterprise.getOrganizationDirectory().getOrganizationList()){
        
               if(o instanceof DoctorOrganization)
               {
                   DoctorOrganization doctorOrganization = (DoctorOrganization)o;
            for(Doctor d : o.getPersonDirectory().getDoctorList())
            {
       
                 Object [] row = new Object[5];
                 row[0] = ua.getPerson().getSsn();
                 row[1] = ua.getPerson();
                 row[2] = d.getQualification();
                 row[3] = d.getContactNo();
                 row[4] = d.getAddress().getStreetName() + " " + d.getAddress().getCity() + " " + d.getAddress().getState() + " " + d.getAddress().getZipcode();
                 model.addRow(row);
          }
               }
        }
        }
    */
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorJTable = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 24, -1, -1));

        doctorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SSN", "Doctor Name", "Specialization", "Contact No", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(doctorJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 74, 688, 146));
        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 886, 417, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 21, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable doctorJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
