/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Sites;

import business.Enterprise.SiteEnterprise;
import business.Organization.Organization;
import business.Organization.PatientOrganization;
import business.Patient.Encounter;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManagePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatientJPanel
     */
    private JPanel userProcessContainer;
    private SiteEnterprise siteEnterprise;
    
    public ManagePatientJPanel( JPanel userProcessContainer,SiteEnterprise siteEnterprise) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.siteEnterprise = siteEnterprise;
        populatePateintTable();
    }
    
    private void populatePateintTable()
    {
        DefaultTableModel model = (DefaultTableModel) patientJTable.getModel();
        model.setRowCount(0);
        
        for(Organization o : siteEnterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(o instanceof PatientOrganization)
            {
                PatientOrganization organization = (PatientOrganization)o;
                for(UserAccount ua : organization.getUserAccountDirectory().getUserAccountList())
                {
                
                    Object [] row = new Object[3];
                    row[0] = ua.getPerson().getSsn();
                    row[1] = ua.getPerson();
                    row[2] = ua;
                    model.addRow(row);
                
                }
                
            }
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Patient ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 29, -1, -1));

        patientJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "SSN", "Patient Name", "UserName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 77, -1, 118));

        backJButton.setText("<<Back ");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:

    
        userProcessContainer.remove(this);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientJTable;
    // End of variables declaration//GEN-END:variables
}
