/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Distributor;

import business.EcoSystem;
import business.Enterprise.DistributorEnterprise;
import business.Organization.Organization;
import business.Organization.ShippingOrganization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.SystemAdmin.ManageStateNetworkJPanel;

/**
 *
 * @author Abhishek
 */
public class DistributorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DistributorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private DistributorEnterprise distributorEnterprise;
    private UserAccount userAccount;
    private ShippingOrganization shippingOrganization;
    public DistributorWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system,DistributorEnterprise distributorEnterprise,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.distributorEnterprise = distributorEnterprise;
        this.userAccount = userAccount;
        this.system = system;
     
        for(Organization o : distributorEnterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(o instanceof ShippingOrganization)
            {
                this.shippingOrganization = (ShippingOrganization)o;
            
            }
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageWarehouseJButton = new javax.swing.JButton();
        manageOrderJButton = new javax.swing.JButton();
        managePaymentJButton = new javax.swing.JButton();
        manageManufacturerEnrollmentJButton = new javax.swing.JButton();
        manageDistributorPersonJButton = new javax.swing.JButton();
        manageDistributorUserAccountJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel1.setText("Distributor Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        manageWarehouseJButton.setText("Manage WareHouse");
        manageWarehouseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWarehouseJButtonActionPerformed(evt);
            }
        });
        add(manageWarehouseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 174, 223, -1));

        manageOrderJButton.setText("Manage Orders");
        manageOrderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrderJButtonActionPerformed(evt);
            }
        });
        add(manageOrderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 325, 223, 30));

        managePaymentJButton.setText("Manage Payment");
        managePaymentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePaymentJButtonActionPerformed(evt);
            }
        });
        add(managePaymentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 223, -1));

        manageManufacturerEnrollmentJButton.setText("Manage Manufacturer Enrollment");
        manageManufacturerEnrollmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageManufacturerEnrollmentJButtonActionPerformed(evt);
            }
        });
        add(manageManufacturerEnrollmentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 122, -1, -1));

        manageDistributorPersonJButton.setText("Manage Distributor Person");
        manageDistributorPersonJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDistributorPersonJButtonActionPerformed(evt);
            }
        });
        add(manageDistributorPersonJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 217, 223, -1));

        manageDistributorUserAccountJButton.setText("Manage Distributor User Account");
        manageDistributorUserAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDistributorUserAccountJButtonActionPerformed(evt);
            }
        });
        add(manageDistributorUserAccountJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 269, 223, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageWarehouseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWarehouseJButtonActionPerformed
        // TODO add your handling code here:
        ManageWareHouseJPanel mwhjp = new ManageWareHouseJPanel(userProcessContainer, system, distributorEnterprise);
        userProcessContainer.add("ManageWareHouseJPanel", mwhjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageWarehouseJButtonActionPerformed

    private void manageManufacturerEnrollmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageManufacturerEnrollmentJButtonActionPerformed
        // TODO add your handling code here:
        
        ManageManufacturerEnrollmentsJPanel mmejp = new ManageManufacturerEnrollmentsJPanel(userProcessContainer, system, distributorEnterprise,userAccount);
        userProcessContainer.add("ManageManufacturerEnrollmentsJPanel", mmejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageManufacturerEnrollmentJButtonActionPerformed

    private void manageOrderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrderJButtonActionPerformed
        // TODO add your handling code here:
        ManageManufacturerSelectionJPanel mmsjp = new ManageManufacturerSelectionJPanel(userProcessContainer,userAccount,distributorEnterprise, system);
        userProcessContainer.add("ManageManufacturerSelectionJPanel", mmsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrderJButtonActionPerformed

    private void manageDistributorUserAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDistributorUserAccountJButtonActionPerformed
        // TODO add your handling code here:
        ManageDistributorUserAccountJPanel mduajp = new ManageDistributorUserAccountJPanel(userProcessContainer,distributorEnterprise);
        userProcessContainer.add("ManageDistributorUserAccountJPanel", mduajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDistributorUserAccountJButtonActionPerformed

    private void manageDistributorPersonJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDistributorPersonJButtonActionPerformed
        // TODO add your handling code here:
          ManageDistributorPersonJPanel mdpjp = new ManageDistributorPersonJPanel(userProcessContainer,distributorEnterprise);
        userProcessContainer.add("ManageDistributorPersonJPanel", mdpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageDistributorPersonJButtonActionPerformed

    private void managePaymentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePaymentJButtonActionPerformed
        // TODO add your handling code here:
        ManageDistributorPaymentAccountJPanel mdpajp = new ManageDistributorPaymentAccountJPanel(userProcessContainer,system,distributorEnterprise,userAccount);
        userProcessContainer.add("ManageDistributorPaymentAccountJPanel", mdpajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePaymentJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageDistributorPersonJButton;
    private javax.swing.JButton manageDistributorUserAccountJButton;
    private javax.swing.JButton manageManufacturerEnrollmentJButton;
    private javax.swing.JButton manageOrderJButton;
    private javax.swing.JButton managePaymentJButton;
    private javax.swing.JButton manageWarehouseJButton;
    // End of variables declaration//GEN-END:variables
}
