/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Distributor;



import business.EcoSystem;
import business.Enterprise.DistributorEnterprise;
import business.Enterprise.SiteEnterprise;
import business.PaymentTransaction.BankAccount;
import business.PaymentTransaction.Transaction;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class DistributorOrderBillPaymentJPanel extends javax.swing.JPanel {
    
    private JPanel upc;
    private UserAccount userAcc;
    private EcoSystem system;
    private DistributorEnterprise distributorEnterprise;

    /**
     * Creates new form BillPaymentPanel
     */
    public DistributorOrderBillPaymentJPanel(JPanel upc,UserAccount userAcc,DistributorEnterprise distributorEnterprise, EcoSystem system) {
        initComponents();
        this.upc = upc;
        this.userAcc = userAcc;
        this.distributorEnterprise = distributorEnterprise;
        this.system = system;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblPayments.getModel();
        dtm.setRowCount(0);
        try
        {
        for(WorkRequest req : userAcc.getWorkQueue().getWorkRequestList()){
            if(req.getOrder()!=null){
                if(req.getOrder().getStatus().equals("Order Approved And Shipped"))
                {
                if(req.getSender().equals(userAcc)){
                    if(req.getOrder().getIsPaid().equals("NO")){
                        Object[] row = new Object[4];
                        row[0] = req.getOrder().getOrderNumber();
                        row[1] = req.getOrder().getBillAmount();
                        row[2] = req.getOrder().getTimeStamp();
                        row[3] = req.getReceiver().getAccountNumber();
                        dtm.addRow(row);
                    }
                    
                }
            }
            }
        }
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(null,"No Bills found!");
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayments = new javax.swing.JTable();
        btnPay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Payment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        tblPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order Id", "Amount Due", "Order Date", "Pay To"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPayments);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 430, 152));

        btnPay.setText("Make Payment");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 130, 30));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPayments.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select an order to pay the bill!");
        }else{
            float amount = (float)tblPayments.getValueAt(selectedRow, 1);
            BankAccount acc = (BankAccount) tblPayments.getValueAt(selectedRow, 3);
            String orderId = (String) tblPayments.getValueAt(selectedRow, 0);
            if(amount > userAcc.getAccountNumber().getBalance()){
                JOptionPane.showMessageDialog(null, "Not enough balance to pay the bill!");
            }
            else{
                float bal = userAcc.getAccountNumber().getBalance();
                bal = bal - amount;
                userAcc.getAccountNumber().setBalance(bal);
                
                float recievedAmt = acc.getBalance();
                recievedAmt = recievedAmt + amount;
                acc.setBalance(recievedAmt);
                
                Transaction t = new Transaction();
                t.setAmount(amount);
                t.setFromAccount(userAcc.getAccountNumber());
                t.setToAccount(acc);
                Calendar cal = Calendar.getInstance();
                t.setDate(cal.getTime());
                t.setOrderId(orderId);
                
                userAcc.getAccountNumber().getTransaction().add(t);
                acc.getTransaction().add(t);
                
                for(WorkRequest req : userAcc.getWorkQueue().getWorkRequestList()){
                    if(req.getOrder() != null){
                        if(req.getOrder().getOrderNumber().equals(orderId)){
                            req.getOrder().setIsPaid("YES");
                        }
                    }
                }
                
                JOptionPane.showMessageDialog(null, "Payment Successful!");
            }
        }
        populateTable();
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) upc.getLayout();
        upc.remove(this);
        layout.previous(upc);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayments;
    // End of variables declaration//GEN-END:variables
}
