/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Distributor;


import business.Enterprise.DistributorEnterprise;
import userInterface.Manufacturer.*;
import business.Enterprise.ManufacturerEnterprise;
import userInterface.SystemAdmin.*;

import business.Organization.Organization;
import business.Organization.OrganizationDirectory;
import business.Organization.ShippingOrganization;
import business.Person.Person;
import business.Person.PersonDirectory;

import business.Role.ShippingRole;
import business.UserAccount.UserAccount;
import business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageDistributorUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSiteUserAccountJPanel
     */
    private JPanel userProcessContainer;
    private UserAccountDirectory userAccountDirectory;
    private PersonDirectory personDirectory;
    private OrganizationDirectory  organizationDirectory;
    private DistributorEnterprise distributorEnterprise;
    
    
    public ManageDistributorUserAccountJPanel(JPanel userProcessContainer, DistributorEnterprise distributorEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = distributorEnterprise.getOrganizationDirectory();
       this.distributorEnterprise = distributorEnterprise;
       for(Organization o : organizationDirectory.getOrganizationList())
       {
           if(o instanceof ShippingOrganization)
           {

              this.userAccountDirectory = o.getUserAccountDirectory();
           }
       }
        this.personDirectory = distributorEnterprise.getPersonDirectory();
        addUserJLayeredPane.setVisible(false);
        organizationJTextField.setText(Organization.Type.Shipping.getValue());
        populateTable();
         populatePersonCombo();
        populateStatusCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        addUserAccountJButton = new javax.swing.JButton();
        activateJButton = new javax.swing.JButton();
        deactivateJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccounts = new javax.swing.JTable();
        viewDetailsJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        addUserJLayeredPane = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUname = new javax.swing.JTextField();
        comboPerson = new javax.swing.JComboBox();
        txtPwd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        organizationJTextField = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();

        jLabel7.setText("Select Person");

        addUserAccountJButton.setText("Add New User Account");
        addUserAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserAccountJButtonActionPerformed(evt);
            }
        });

        activateJButton.setText("Activate Account");
        activateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateJButtonActionPerformed(evt);
            }
        });

        deactivateJButton.setText("Deactivate Account");
        deactivateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage User Accounts");

        tblUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "User Name", "Role", "Organization", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccounts);

        viewDetailsJButton.setText("View Details");
        viewDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        addUserJLayeredPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Status");
        addUserJLayeredPane.add(jLabel9);
        jLabel9.setBounds(130, 340, 36, 20);

        jLabel4.setText("Name");
        addUserJLayeredPane.add(jLabel4);
        jLabel4.setBounds(140, 190, 50, 16);

        jLabel3.setText("Select Person");
        addUserJLayeredPane.add(jLabel3);
        jLabel3.setBounds(100, 120, 80, 20);

        txtName.setEditable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(txtName);
        txtName.setBounds(200, 180, 120, 30);
        addUserJLayeredPane.add(txtUname);
        txtUname.setBounds(200, 220, 120, 30);

        comboPerson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPersonActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(comboPerson);
        comboPerson.setBounds(200, 110, 150, 30);
        addUserJLayeredPane.add(txtPwd);
        txtPwd.setBounds(200, 260, 120, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Add New User Accounts");
        addUserJLayeredPane.add(jLabel2);
        jLabel2.setBounds(110, 20, 190, 22);

        jLabel5.setText("User Name");
        addUserJLayeredPane.add(jLabel5);
        jLabel5.setBounds(110, 230, 70, 16);

        jLabel6.setText("Password");
        addUserJLayeredPane.add(jLabel6);
        jLabel6.setBounds(120, 270, 60, 16);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(comboStatus);
        comboStatus.setBounds(200, 330, 150, 30);

        jLabel11.setText("Organization");
        addUserJLayeredPane.add(jLabel11);
        jLabel11.setBounds(100, 70, 72, 16);

        organizationJTextField.setEditable(false);
        organizationJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJTextFieldActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(organizationJTextField);
        organizationJTextField.setBounds(200, 62, 150, 30);

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(addJButton);
        addJButton.setBounds(190, 410, 55, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(backJButton)
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(activateJButton)
                                .addGap(63, 63, 63)
                                .addComponent(deactivateJButton)
                                .addGap(66, 66, 66)
                                .addComponent(addUserAccountJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(addUserJLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63)
                        .addComponent(viewDetailsJButton)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backJButton))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activateJButton)
                    .addComponent(deactivateJButton)
                    .addComponent(addUserAccountJButton)
                    .addComponent(viewDetailsJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(addUserJLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void populateTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) tblUserAccounts.getModel();
        dtm.setRowCount(0);
        
       
        for(Organization organization : organizationDirectory.getOrganizationList()){
            for(UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()){
                Object[] row = new Object[6];
                row[0] = ua.getPerson().getFirstName();
                row[1] = ua.getPerson().getLastName();
                row[2] = ua;
                row[3] = ua.getRole().getRoleName();
                row[4] = organization.getName();
                row[5] = ua.getStatus();
                dtm.addRow(row);
        
            }
        }
        
    }
    
      public void populatePersonCombo(){
         comboPerson.removeAllItems();
        
        for(Person p : personDirectory.getPersonList()){
            comboPerson.addItem(p);
        }
    }
    

    
     public void populateStatusCombo(){
        comboStatus.removeAllItems();
        
        comboStatus.addItem(UserAccount.ACTIVE);
        comboStatus.addItem(UserAccount.DEACTIVE);
    }
    
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addUserAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserAccountJButtonActionPerformed
        // TODO add your handling code here:
          addUserJLayeredPane.setVisible(true);
        
    }//GEN-LAST:event_addUserAccountJButtonActionPerformed

    private void deactivateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateJButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblUserAccounts.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }else{
            UserAccount ua = (UserAccount) tblUserAccounts.getValueAt(selectedRow, 2);
            ua.setStatus(UserAccount.DEACTIVE);
            populateTable();
        }
    }//GEN-LAST:event_deactivateJButtonActionPerformed

    private void activateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateJButtonActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblUserAccounts.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
            return;
        }
            UserAccount ua = (UserAccount) tblUserAccounts.getValueAt(selectedRow, 2);
            ua.setStatus(UserAccount.ACTIVE);
            populateTable();
        
    }//GEN-LAST:event_activateJButtonActionPerformed

    private void viewDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsJButtonActionPerformed
        // TODO add your handling code here:
          int selectedRow = tblUserAccounts.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
            return;
        }
        UserAccount ua = (UserAccount) tblUserAccounts.getValueAt(selectedRow, 2);
        
        ViewUserAccountDetailsJPanel vuadjp = new ViewUserAccountDetailsJPanel(userProcessContainer,ua);
        userProcessContainer.add("ViewUserAccountDetailsJPanel", vuadjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_viewDetailsJButtonActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    private void comboPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPersonActionPerformed
        // TODO add your handling code here:
        Person p = (Person)comboPerson.getSelectedItem();
         
        if(p!=null)
        {
            txtName.setText(p.getFirstName()+" "+p.getLastName());
        
        }
    }//GEN-LAST:event_comboPersonActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void organizationJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationJTextFieldActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        
        String uname = txtUname.getText().trim();
        String pwd = txtPwd.getText().trim();
        Person person = (Person) comboPerson.getSelectedItem();

        String status = (String) comboStatus.getSelectedItem();

        if(!uname.isEmpty()){
            if(!pwd.isEmpty()){
                if(comboPerson.getSelectedItem()!=null)
                {
                
                    boolean flag = userAccountDirectory.checkIfUsernameIsUnique(uname,userAccountDirectory.getUserAccountList());
                    if(flag == false){

                        UserAccount ua = userAccountDirectory.createUserAccount(uname, pwd,person,null);
                        ua.setStatus(status);

                        ua.setRole(new ShippingRole());
                        addUserJLayeredPane.setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "User Name already exists!");
                    }
                }
                else{
                        JOptionPane.showMessageDialog(null, "Create a person before assigning him an user account");
                    }
                
            }else{
                JOptionPane.showMessageDialog(null, "Enter A Password");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Enter A User Name");
        }
        populateTable();
        
    }//GEN-LAST:event_addJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateJButton;
    private javax.swing.JButton addJButton;
    private javax.swing.JButton addUserAccountJButton;
    private javax.swing.JLayeredPane addUserJLayeredPane;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox comboPerson;
    private javax.swing.JComboBox comboStatus;
    private javax.swing.JButton deactivateJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField organizationJTextField;
    private javax.swing.JTable tblUserAccounts;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPwd;
    private javax.swing.JTextField txtUname;
    private javax.swing.JButton viewDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
