/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Distributor;

import business.Distributor.Warehouse;
import business.EcoSystem;
import business.Enterprise.DistributorEnterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */

public class ManageWareHouseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageWareHouseJPanel
     */
    private JPanel userProcessContainer;
    private DistributorEnterprise distributorEnterprise;
    private EcoSystem system;
    public ManageWareHouseJPanel(JPanel userProcessContainer,EcoSystem system,DistributorEnterprise distributorEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.distributorEnterprise = distributorEnterprise;
        this.system = system;
        populateWarehouseTable();
        populateRegionComboBox();
    }
    
    
    private void populateWarehouseTable() {
        DefaultTableModel model = (DefaultTableModel) tblWarehouses.getModel();
        model.setRowCount(0);
        
        if(!distributorEnterprise.getWarehouseList().isEmpty())
        {
            for(Warehouse w : distributorEnterprise.getWarehouseList())
            {
                Object [] row = new Object[2];
                row[0] = w;
                row[1] = w.getWarehouseRegion();
                model.addRow(row);
            
            }
        
        }
    }

    private void populateRegionComboBox() {
        
        comboRegion.removeAllItems();
        comboRegion.addItem("NORTHEAST");
        comboRegion.addItem("WEST");
        comboRegion.addItem("MIDWEST");
        comboRegion.addItem("SOUTH");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewInventory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWarehouses = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboRegion = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnAddWareHouse = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewInventory.setText("View Warehouse Inventory");
        btnViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInventoryActionPerformed(evt);
            }
        });
        add(btnViewInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 208, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Warehouses");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 51, -1, -1));

        tblWarehouses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Region"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWarehouses);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 116, 337, 79));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 51, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Add New Warehouse");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        comboRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel3.setText("Select Region");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        btnAddWareHouse.setText("Add Warehouse");
        btnAddWareHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWareHouseActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddWareHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 277, 287, 171));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInventoryActionPerformed
        // TODO add your handling code here:
        int rowSelected = tblWarehouses.getSelectedRow();
        
        if(rowSelected<0)
        {
            JOptionPane.showMessageDialog(null,"No row selected!");
            return;
        
        }
        Warehouse w = (Warehouse) tblWarehouses.getValueAt(rowSelected, 0);
        
        ViewWarehouseInventoryJPanel vwijp = new ViewWarehouseInventoryJPanel(userProcessContainer,system,w);
        userProcessContainer.add("ViewWarehouseInventoryJPanel", vwijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnViewInventoryActionPerformed

    private void btnAddWareHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWareHouseActionPerformed
        // TODO add your handling code here:
        
        String region = (String) comboRegion.getSelectedItem();
        boolean flag = false;
        
        if(!distributorEnterprise.getWarehouseList().isEmpty())
        {
            for(Warehouse w : distributorEnterprise.getWarehouseList())
            {
                if(w.getWarehouseRegion().equals(region))
                {
                    flag = true;
                
                }
            
            }
        
        }
        
        
        if(flag == false)
        {
            Warehouse w = new Warehouse();
            w.setWarehouseRegion(region);
            distributorEnterprise.getWarehouseList().add(w);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "There is a warehouse in this region");
            
        }
        
        populateWarehouseTable();
    }//GEN-LAST:event_btnAddWareHouseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWareHouse;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewInventory;
    private javax.swing.JComboBox comboRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWarehouses;
    // End of variables declaration//GEN-END:variables

    
}
