/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Distributor;

import business.Distributor.Warehouse;
import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.ManufacturerEnterprise;
import business.Vaccine.Batch;
import business.Vaccine.Vaccine;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Abhishek
 */
public class ViewWarehouseInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewWarehouseInventoryJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Warehouse warehouse;
    public ViewWarehouseInventoryJPanel(JPanel userProcessContainer,EcoSystem system,Warehouse warehouse) { 
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.warehouse = warehouse;
        txtRegion.setText(warehouse.getWarehouseRegion());
       
        populateWarehouseInventory();
    }

    public void populateWarehouseInventory()
    {
    
        DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
        model.setRowCount(0);
        
        for(Batch b : warehouse.getBatchDirectory().getBatchList())
        {
            for(Vaccine v : b.getVaccineList())
            {
                Object [] row = new Object[7];
                row[0] = v.getVaccineType();
                row[1] = v.getVaccineName();
                row[2] = b.getBatchID();
                row[4] = b.getManufacturerInventoryStatus();
                row[5] = v.getvPrice();
                row[6] = v.getVaccineType().getFundingInfo();
                
                for(Enterprise e : system.getEnterpriseDirectory().getEnterpriseList())
                {
                    if(e instanceof ManufacturerEnterprise)
                    {
                        ManufacturerEnterprise manufacturerEnterprise = (ManufacturerEnterprise)e;
                        for(Batch batch : manufacturerEnterprise.getBatchDirectory().getBatchList())
                        {
                            if(b.getBatchID().equals(batch.getBatchID()))
                            {
                                row[3] = manufacturerEnterprise.getName();
                                break;
                            }
                        
                        }
                    
                    }
                    
                }
            
                model.addRow(row);
                break;
            }
        
        }
        
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtRegion = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Vaccine Type", "Name", "Batch", "Manufacturer", "Status", "Price", "Funding"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventory);

        jLabel2.setText("Region");

        txtRegion.setEditable(false);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Warehouse Inventory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnBack)
                .addGap(142, 142, 142)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtRegion;
    // End of variables declaration//GEN-END:variables
}
