/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Provider;


import business.EcoSystem;
import business.Enterprise.ProviderEnterprise;
import business.PaymentTransaction.Transaction;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageProviderAccountsJPanel extends javax.swing.JPanel {
    
    private JPanel upc;
    private EcoSystem system;
    private UserAccount userAccount;
    private ProviderEnterprise providerEnterprise;

    /**
     * Creates new form ManageAccountsPanel
     */
    public ManageProviderAccountsJPanel(JPanel upc,EcoSystem system,UserAccount userAccount,ProviderEnterprise providerEnterprise) {
        initComponents();
        this.upc = upc;
        this.system = system;
        this.userAccount = userAccount;
        this.providerEnterprise = providerEnterprise;
        populateTextBox();
    }
    
    public void populateTextBox(){
        txtAccNum.setText(userAccount.getAccountNumber().getAccountNumber());
        txtBalance.setText(String.valueOf(userAccount.getAccountNumber().getBalance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtBalance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransactionHist = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtAccNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnDeposit = new javax.swing.JButton();
        btnPaid = new javax.swing.JButton();
        btnRecieved = new javax.swing.JButton();
        btnPayBills = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Accounts And Payments");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtBalance.setEditable(false);
        add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 126, -1));

        jLabel2.setText("Account Balance");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        tblTransactionHist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "From Account", "To Account", "Date", "Amount", "Order Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTransactionHist);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 580, 170));

        jLabel3.setText("Account Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        txtAccNum.setEditable(false);
        txtAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccNumActionPerformed(evt);
            }
        });
        add(txtAccNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 126, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Transaction History");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Deposit Money");

        jLabel6.setText("Amount");

        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel5))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel6)
                        .addGap(45, 45, 45)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnDeposit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeposit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtAmount, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnDeposit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

        btnPaid.setText("View Paid Bills");
        btnPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaidActionPerformed(evt);
            }
        });
        add(btnPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        btnRecieved.setText("View Recieved Bills");
        btnRecieved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecievedActionPerformed(evt);
            }
        });
        add(btnRecieved, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 160, -1));

        btnPayBills.setText("Pay Bills");
        btnPayBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayBillsActionPerformed(evt);
            }
        });
        add(btnPayBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here
        CardLayout layout = (CardLayout) upc.getLayout();
        upc.remove(this);
        layout.previous(upc);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        try{
            float amt = Float.parseFloat(txtAmount.getText());

            float bal = userAccount.getAccountNumber().getBalance();
            bal = bal + amt;
            userAccount.getAccountNumber().setBalance(bal);
            populateTextBox();
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter the appropriate balance amount to be deposited! ");
        }
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaidActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblTransactionHist.getModel();
        dtm.setRowCount(0);

        for(Transaction t : userAccount.getAccountNumber().getTransaction()){
            if(t.getFromAccount().equals(userAccount.getAccountNumber())){
                Object[] row = new Object[5];
                row[0] = t.getFromAccount();
                row[1] = t.getToAccount();
                row[2] = t.getDate();
                row[3] = t.getAmount();
                row[4] = t.getOrderId();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_btnPaidActionPerformed

    private void btnRecievedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecievedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblTransactionHist.getModel();
        dtm.setRowCount(0);

        for(Transaction t : userAccount.getAccountNumber().getTransaction()){
            if(t.getToAccount().equals(userAccount.getAccountNumber())){
                Object[] row = new Object[5];
                row[0] = t.getToAccount();
                row[1] = t.getFromAccount();
                row[2] = t.getDate();
                row[3] = t.getAmount();
                row[4] = t.getOrderId();
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_btnRecievedActionPerformed

    private void btnPayBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayBillsActionPerformed
        // TODO add your handling code here:
        ManageProviderBillPaymentJPanel mpbpjp = new ManageProviderBillPaymentJPanel(upc,providerEnterprise, userAccount , system);
        CardLayout layout = (CardLayout) upc.getLayout();
        upc.add("ManageProviderBillPaymentJPanel", mpbpjp);
        layout.next(upc);
    }//GEN-LAST:event_btnPayBillsActionPerformed

    private void txtAccNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnPaid;
    private javax.swing.JButton btnPayBills;
    private javax.swing.JButton btnRecieved;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransactionHist;
    private javax.swing.JTextField txtAccNum;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBalance;
    // End of variables declaration//GEN-END:variables
}
