/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.Provider;

import business.Enterprise.Enterprise;
import business.Enterprise.PHDEnterprise;
import business.Enterprise.ProviderEnterprise;
import business.Network.CityNetwork;
import business.UserAccount.UserAccount;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageProviderEnrollmentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageProviderEnrollmentsJPanel
     */
    private JPanel userProcessContainer;
    private ProviderEnterprise providerEnterprise;
    private UserAccount userAccount;
    private PHDEnterprise pHDEnterprise;
    
    public ManageProviderEnrollmentsJPanel(JPanel userProcessContainer,ProviderEnterprise providerEnterprise, UserAccount userAccount, PHDEnterprise pHDEnterprise ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.providerEnterprise = providerEnterprise;
        this.userAccount = userAccount;
        this.pHDEnterprise = pHDEnterprise;
        populateProviderTable();
    }
    
    public void populateProviderTable()
    {
        DefaultTableModel model = (DefaultTableModel) tableProviderEnrollments.getModel();
        model.setRowCount(0);
        
        if(!providerEnterprise.getWorkQueue().getWorkRequestList().isEmpty())
        {
            for(WorkRequest request : providerEnterprise.getWorkQueue().getWorkRequestList())
            {
                for(CityNetwork cityNetwork : pHDEnterprise.getCityNetworkDirectory().getCityNetworkDirectory())
                {
                    for(Enterprise e : cityNetwork.getEnterpriseDirectory().getEnterpriseList())
                    {
                        if(!e.getUserAccountDirectory().getUserAccountList().isEmpty())
                        {
                            for(UserAccount ua : e.getUserAccountDirectory().getUserAccountList())
                            {
                                if(request.getSender().equals(ua))
                                {
                                    Object [] row = new Object[4];
                                    row[0] = e.getOrganizationID();
                                    row[1] = e.getName();
                                    row[2] = ua.getPerson().getFirstName()+" "+ua.getPerson().getLastName();
                                    row[3] = request;
                                    model.addRow(row);
                                
                                }
                            
                            }
                        
                        }
                    
                    }
                
                }
            
            }
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProviderEnrollments = new javax.swing.JTable();
        btnApproveEnrollment = new javax.swing.JButton();
        btnDeclineEnrollment = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Provider Enrollments");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        tableProviderEnrollments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Site Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableProviderEnrollments);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 64, 450, 93));

        btnApproveEnrollment.setText("Approve Enrollment");
        btnApproveEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveEnrollmentActionPerformed(evt);
            }
        });
        add(btnApproveEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        btnDeclineEnrollment.setText("Decline Enrollment");
        btnDeclineEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineEnrollmentActionPerformed(evt);
            }
        });
        add(btnDeclineEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 145, -1));

        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApproveEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveEnrollmentActionPerformed
        // TODO add your handling code here:
        int rowSelected = tableProviderEnrollments.getSelectedRow();
        if(rowSelected<0)
        {
            JOptionPane.showMessageDialog(null, "No row selected");
            return;
        }
        WorkRequest request = (WorkRequest) tableProviderEnrollments.getValueAt(rowSelected, 3);
        request.setStatus("Approved");
        request.setReceiver(userAccount);
        populateProviderTable();
    }//GEN-LAST:event_btnApproveEnrollmentActionPerformed

    private void btnDeclineEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineEnrollmentActionPerformed
        // TODO add your handling code here:
        
          int rowSelected = tableProviderEnrollments.getSelectedRow();
        if(rowSelected<0)
        {
            JOptionPane.showMessageDialog(null, "No row selected");
            return;
        }
        WorkRequest request = (WorkRequest) tableProviderEnrollments.getValueAt(rowSelected, 3);
        request.setStatus("Declined");
        request.setReceiver(userAccount);
        populateProviderTable();
    }//GEN-LAST:event_btnDeclineEnrollmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveEnrollment;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeclineEnrollment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProviderEnrollments;
    // End of variables declaration//GEN-END:variables
}
