/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Provider;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.PHDEnterprise;
import business.Enterprise.ProviderEnterprise;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.SystemAdmin.ManageCDCPersonJPanel;

/**
 *
 * @author Abhishek
 */
public class ProviderWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProviderWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private ProviderEnterprise providerEnterprise;
    private UserAccount userAccount;
    private PHDEnterprise pHDEnterprise;
    
    public ProviderWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount, ProviderEnterprise providerEnterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.providerEnterprise = providerEnterprise;
        this.userAccount =userAccount;
        
    }
    
    public void getStatePHD()
    {
    
        for(Enterprise e : system.getEnterpriseDirectory().getEnterpriseList())
        {
        
            if(e instanceof PHDEnterprise)
            {
                PHDEnterprise phde = (PHDEnterprise) e;
                for(Enterprise en : phde.getEnterpriseDirectory().getEnterpriseList())
                {
                    if(en instanceof ProviderEnterprise && providerEnterprise.equals(en))
                    {
                        this.pHDEnterprise = phde;
                    
                    }
                
                }
            
            }
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageOrdersJButton = new javax.swing.JButton();
        managePaymentJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel1.setText("Provider Work Area ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 36, -1, -1));

        manageOrdersJButton.setText("Manage Orders");
        manageOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersJButtonActionPerformed(evt);
            }
        });
        add(manageOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 132, 175, -1));

        managePaymentJButton.setText("Manage Payments");
        managePaymentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePaymentJButtonActionPerformed(evt);
            }
        });
        add(managePaymentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 183, 175, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void managePaymentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePaymentJButtonActionPerformed
        // TODO add your handling code here:
        ManageProviderAccountsJPanel mpajp = new ManageProviderAccountsJPanel(userProcessContainer,system,userAccount,providerEnterprise);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageProviderAccountsJPanel", mpajp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePaymentJButtonActionPerformed

    private void manageOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersJButtonActionPerformed
        // TODO add your handling code here:
        ManageProviderOrdersJPanel mpojp = new ManageProviderOrdersJPanel(userProcessContainer,providerEnterprise,userAccount,system);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageProviderOrdersJPanel", mpojp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrdersJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageOrdersJButton;
    private javax.swing.JButton managePaymentJButton;
    // End of variables declaration//GEN-END:variables
}
