/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.PHD;


import business.Enterprise.PHDEnterprise;
import business.Network.CityNetwork;
import business.Network.CityNetworkDirectory;
import business.Network.StateNetwork;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageCityNetworkJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CityNetworkDirectory cityNetworkDirectory;
    private StateNetwork stateNetwork;
    private PHDEnterprise phdEnterprise;
    
    /**
     * Creates new form ManageCityNetworkPanel
     */
    public ManageCityNetworkJPanel(JPanel userProcessContainer,StateNetwork stateNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.stateNetwork = stateNetwork;
        this.phdEnterprise = stateNetwork.getState().getStatePHD();
        this.cityNetworkDirectory = phdEnterprise.getCityNetworkDirectory();
        txtState.setText(stateNetwork.getState().getName());
        txtState.setEditable(false);
        populateTbl();
    }
    
    private void populateTbl(){
        DefaultTableModel dtm = (DefaultTableModel) tblCity.getModel();
        dtm.setRowCount(0);
        
        for(CityNetwork cn : cityNetworkDirectory.getCityNetworkDirectory()){
            Object[] row = new Object[1];
            row[0] = cn;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCity = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        btnAddCity = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage City Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 48, -1, -1));

        tblCity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCity);
        if (tblCity.getColumnModel().getColumnCount() > 0) {
            tblCity.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 91, 257, 100));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 48, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Start A New City Network");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel3.setText("City");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, -1));

        btnAddCity.setText("Add City");
        btnAddCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCityActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel4.setText("State");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtState.setEditable(false);
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });
        jPanel1.add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 280, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCityActionPerformed
        // TODO add your handling code here:
        String name = txtCity.getText().trim();
        boolean flag = false;
        
        if(!name.isEmpty()){
            if(!cityNetworkDirectory.getCityNetworkDirectory().isEmpty()){
                for(CityNetwork cn : cityNetworkDirectory.getCityNetworkDirectory()){
                    if(cn.getCityName().equals(name)){
                        JOptionPane.showMessageDialog(null, "City already exists!");
                        flag = true;
                    }   
                }
            }else{
                CityNetwork city = cityNetworkDirectory.addCityNetwork(name);
                city.setInState(stateNetwork.getState().getName());
                flag = true;
            }
        }else{
            JOptionPane.showMessageDialog(null, "Enter a name for the city!");
            flag = true;
        }
        
        if(flag == false){
            CityNetwork city = cityNetworkDirectory.addCityNetwork(name);
            city.setInState(stateNetwork.getState().getName());
        }
        
        populateTbl();
        txtCity.setText("");
    }//GEN-LAST:event_btnAddCityActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCity;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCity;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables
}
