/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PHD;

import business.Enterprise.Enterprise;
import business.Enterprise.EnterpriseDirectory;
import business.Enterprise.PHDEnterprise;
import business.Enterprise.SiteEnterprise;
import business.Network.CityNetwork;
import business.Person.Person;
import business.Person.PersonDirectory;
import business.Role.ProviderRole;
import business.Role.SiteAdminRole;
import business.UserAccount.UserAccount;
import business.UserAccount.UserAccountDirectory;
import business.Utility.SendEmail;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManagePHDUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePHDUserAccountJPanel
     */
    
     private JPanel userProcessContainer;
    private UserAccountDirectory userAccDir;
    private EnterpriseDirectory entDir;
    private PersonDirectory pd;
    private PHDEnterprise phde;
    public ManagePHDUserAccountJPanel(JPanel upc,UserAccountDirectory userAccDir,EnterpriseDirectory entDir,PersonDirectory pd, PHDEnterprise phde) {
        initComponents();
         this.userProcessContainer = upc;
        this.userAccDir = userAccDir;
        this.entDir = entDir;
        this.pd = pd;
        this.phde = phde;
        
        addUserJLayeredPane.setVisible(false);
        populateTable();
         populatePersonCombo();
        populateEnterpriseCombo();
        populateStatusCombo();
    }
    
    public void populateTable(){
         DefaultTableModel dtm = (DefaultTableModel) tblUserAccounts.getModel();
        dtm.setRowCount(0);
        
       // to show provider
        for(Enterprise e : entDir.getEnterpriseList()){
            for(UserAccount ua : e.getUserAccountDirectory().getUserAccountList()){
                Object[] row = new Object[6];
                row[0] = ua.getPerson().getFirstName();
                row[1] = ua.getPerson().getLastName();
                row[2] = ua;
                row[3] = ua.getRole().getRoleName();
                row[4] = e.getName();
                row[5] = ua.getStatus();
                dtm.addRow(row);
        
            }
        }
        //to show sites
        for(CityNetwork cityNetwork : phde.getCityNetworkDirectory().getCityNetworkDirectory())
        {
        
            for(Enterprise e: cityNetwork.getEnterpriseDirectory().getEnterpriseList())
            {
                for(UserAccount ua : e.getUserAccountDirectory().getUserAccountList())
                {
                
                     Object[] row = new Object[6];
                row[0] = ua.getPerson().getFirstName();
                row[1] = ua.getPerson().getLastName();
                row[2] = ua;
                row[3] = ua.getRole().getRoleName();
                row[4] = e.getName();
                row[5] = ua.getStatus();
                dtm.addRow(row);
                
                }
            
            }
        
        }
        
    }
    
    
    public void populatePersonCombo(){
         comboPerson.removeAllItems();
        
        for(Person p : pd.getPersonList()){
            comboPerson.addItem(p);
        }
    }
    
    public void populateEnterpriseCombo(){
        comboEntType.removeAllItems();
        
        for(Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()){
            if(!type.getValue().equals(Enterprise.EnterpriseType.PHD.getValue())){
                if(!type.getValue().equals(Enterprise.EnterpriseType.Manufacturer.getValue())){
                    if(!type.getValue().equals(Enterprise.EnterpriseType.Distributor.getValue())){
                        if(!type.getValue().equals(Enterprise.EnterpriseType.Clinic.getValue())){
                        comboEntType.addItem(type);
                    }  }
                }
            }
        }
    }
    
     public void populateStatusCombo(){
        comboStatus.removeAllItems();
        
        comboStatus.addItem(UserAccount.ACTIVE);
        comboStatus.addItem(UserAccount.DEACTIVE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccounts = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnActivate = new javax.swing.JButton();
        btnDeactivate = new javax.swing.JButton();
        addUserJLayeredPane = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtUname = new javax.swing.JTextField();
        comboPerson = new javax.swing.JComboBox();
        txtPwd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboEntType = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox();
        comboEntName = new javax.swing.JComboBox();
        viewDetailsJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage PHD User Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 28, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 28, -1, -1));

        tblUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "User Name", "Role", "Enterprise", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccounts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 86, 757, 141));

        btnCreate.setText("Create User Accounts");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 253, -1, -1));

        btnActivate.setText("Activate Account");
        btnActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivateActionPerformed(evt);
            }
        });
        add(btnActivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 253, -1, -1));

        btnDeactivate.setText("Deactivate Account");
        btnDeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeactivateActionPerformed(evt);
            }
        });
        add(btnDeactivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 253, -1, -1));

        addUserJLayeredPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addUserJLayeredPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Enterprise Name");
        addUserJLayeredPane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel9.setText("Status");
        addUserJLayeredPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel4.setText("Name");
        addUserJLayeredPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 50, -1));

        jLabel3.setText("Select Person");
        addUserJLayeredPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 59, -1));

        txtName.setEditable(false);
        addUserJLayeredPane.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, 30));
        addUserJLayeredPane.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, 30));

        comboPerson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPersonActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(comboPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 52, 120, 30));
        addUserJLayeredPane.add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 120, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Add New User Accounts");
        addUserJLayeredPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 190, -1));

        comboEntType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEntType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEntTypeActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(comboEntType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 120, 30));

        jLabel5.setText("User Name");
        addUserJLayeredPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, -1));

        jLabel6.setText("Password");
        addUserJLayeredPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 60, -1));

        jLabel7.setText("Enterprise Type");
        addUserJLayeredPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 120, 30));

        comboEntName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEntName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEntNameActionPerformed(evt);
            }
        });
        addUserJLayeredPane.add(comboEntName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 120, 30));

        add(addUserJLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 330, 387, 408));

        viewDetailsJButton.setText("View Details");
        viewDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsJButtonActionPerformed(evt);
            }
        });
        add(viewDetailsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 253, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        addUserJLayeredPane.setVisible(true);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUserAccounts.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }else{
            UserAccount ua = (UserAccount) tblUserAccounts.getValueAt(selectedRow, 2);
            ua.setStatus(UserAccount.ACTIVE);
            populateTable();
        }
    }//GEN-LAST:event_btnActivateActionPerformed

    private void btnDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeactivateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUserAccounts.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }else{
            UserAccount ua = (UserAccount) tblUserAccounts.getValueAt(selectedRow, 2);
            ua.setStatus(UserAccount.DEACTIVE);
            populateTable();
        }
    }//GEN-LAST:event_btnDeactivateActionPerformed

    private void comboEntNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEntNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEntNameActionPerformed

    private void comboEntTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEntTypeActionPerformed
        // TODO add your handling code here:
        comboEntName.removeAllItems();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) comboEntType.getSelectedItem();
        boolean flag = false;
        
        for(Enterprise e : entDir.getEnterpriseList()){
            if(e.getEnterpriseType().equals(type)){
                comboEntName.addItem(e);
                flag = true;
            }
        }
        
        if(flag == false)
        {
            if(!phde.getCityNetworkDirectory().getCityNetworkDirectory().isEmpty())
            {
            
                for(CityNetwork cityNetwork : phde.getCityNetworkDirectory().getCityNetworkDirectory())
                {
                
                    for(Enterprise e : cityNetwork.getEnterpriseDirectory().getEnterpriseList())
                    {
                    
                        if(e instanceof SiteEnterprise)
                        {
                        
                            comboEntName.addItem(e);
                        }
                    }
                }
            
            }
        
        }
    }//GEN-LAST:event_comboEntTypeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String uname = txtUname.getText().trim();
        String pwd = txtPwd.getText().trim();
        Person person = (Person) comboPerson.getSelectedItem();
        String email = person.getEmailid();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) comboEntType.getSelectedItem();
        Enterprise enterprise = (Enterprise) comboEntName.getSelectedItem();

        String status = (String) comboStatus.getSelectedItem();

      if(comboPerson.getSelectedItem()!=null)
      {
          if(enterprise!=null)
        {
        if(!uname.isEmpty()){
            if(!pwd.isEmpty()){
                boolean flag = userAccDir.checkIfUsernameIsUnique(uname,userAccDir.getUserAccountList());
                if(flag == false){

                    UserAccount ua = enterprise.getUserAccountDirectory().createUserAccount(uname, pwd, person, null);
                    ua.setStatus(status);
                    
                      txtUname.setText("");
                      txtPwd.setText("");
                     addUserJLayeredPane.setVisible(false);
                    if(type.equals(Enterprise.EnterpriseType.Provider)){
                              ua.setRole(new ProviderRole());
                                 String subject="Congratulations, You are now a Approved Provider for "+phde.getStateName()+", USA";
                                 String message="You enterprise login credentials are - userid is :"+uname+" and password is :"+pwd;
                                SendEmail.SendEmail(email,subject, message);
                               
                    }

                    else if(type.equals(Enterprise.EnterpriseType.Site)){
                        ua.setRole(new SiteAdminRole());
                        String subject="Congratulations, You are now a Approved Site for "+phde.getStateName()+", USA";
                                 String message="You enterprise login credentials are - userid is :"+uname+" and password is :"+pwd;
                                SendEmail.SendEmail(email,subject, message);
                    }

                }else{
                    JOptionPane.showMessageDialog(null, "User Name already exists!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Enter A Password");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Enter A User Name");
        }
        }
            else{
            JOptionPane.showMessageDialog(null, "Add an enterprise before creating an user account");
        }
      }
     else
     {
          JOptionPane.showMessageDialog(null, "Add a person before adding an user account");
     }
        populateTable();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    private void comboPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPersonActionPerformed
        // TODO add your handling code here:
        Person p = (Person)comboPerson.getSelectedItem();
         
        if(p!=null)
        {
            txtName.setText(p.getFirstName()+" "+p.getLastName());
        
        }
    }//GEN-LAST:event_comboPersonActionPerformed

    private void viewDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblUserAccounts.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
            return;
        }
        UserAccount ua = (UserAccount) tblUserAccounts.getValueAt(selectedRow, 2);

        ViewUserAccountDetailsJPanel vuadjp = new ViewUserAccountDetailsJPanel(userProcessContainer,ua);
        userProcessContainer.add("ViewUserAccountDetailsJPanel", vuadjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_viewDetailsJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane addUserJLayeredPane;
    private javax.swing.JButton btnActivate;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDeactivate;
    private javax.swing.JComboBox comboEntName;
    private javax.swing.JComboBox comboEntType;
    private javax.swing.JComboBox comboPerson;
    private javax.swing.JComboBox comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserAccounts;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPwd;
    private javax.swing.JTextField txtUname;
    private javax.swing.JButton viewDetailsJButton;
    // End of variables declaration//GEN-END:variables
}
