/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PHD;

import business.Enterprise.Enterprise;
import business.Enterprise.Enterprise.EnterpriseType;
import business.Enterprise.EnterpriseDirectory;
import business.Enterprise.PHDEnterprise;
import business.Enterprise.ProviderEnterprise;
import business.Enterprise.SiteEnterprise;
import business.Role.Role;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageProviderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageProviderJPanel
     */
    
     private JPanel userProcessContainer;
    private PHDEnterprise pHDEnterprise;
    private EnterpriseDirectory enterpriseDirectory;
    
    public ManageProviderJPanel(JPanel userProcessContainer,PHDEnterprise pHDEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pHDEnterprise = pHDEnterprise;
        this.enterpriseDirectory = pHDEnterprise.getEnterpriseDirectory();
       // viewSiteJLayeredPane.setVisible(false);
        addProviderJLayeredPane.setVisible(false);
        enterpriseTypeJTextField.setText(EnterpriseType.Provider.getValue());
        populateTable();
        
    }
    
     
    public void populateTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) providerJTable.getModel();
        dtm.setRowCount(0);
        
        for(Enterprise e : enterpriseDirectory.getEnterpriseList()){
            if(e.getEnterpriseType().equals(Enterprise.EnterpriseType.Provider)){
                Object[] row = new Object[2];
                row[0] = e.getOrganizationID();
                row[1] = e;
                dtm.addRow(row);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        providerJTable = new javax.swing.JTable();
        addProviderJButton = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        addProviderJLayeredPane = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        enterpriseTypeJTextField = new javax.swing.JTextField();
        providerNameJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addProviderJButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Provider");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 35, -1, -1));

        providerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Provider Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(providerJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 78, 552, 140));

        addProviderJButton.setText("Add Provider");
        addProviderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProviderJButtonActionPerformed(evt);
            }
        });
        add(addProviderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 253, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 35, -1, -1));

        addProviderJLayeredPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addProviderJLayeredPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Add Provider");
        addProviderJLayeredPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, -1));

        jLabel7.setText("Name :");
        addProviderJLayeredPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 50, -1));

        enterpriseTypeJTextField.setEditable(false);
        addProviderJLayeredPane.add(enterpriseTypeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 182, 130, 30));

        providerNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerNameJTextFieldActionPerformed(evt);
            }
        });
        addProviderJLayeredPane.add(providerNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 130, 40));

        jLabel9.setText("Enterprise Type :");
        addProviderJLayeredPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 30));

        addProviderJButton1.setText("Add");
        addProviderJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProviderJButton1ActionPerformed(evt);
            }
        });
        addProviderJLayeredPane.add(addProviderJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 265, 70, 30));

        add(addProviderJLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 322, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void addProviderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProviderJButtonActionPerformed
        // TODO add your handling code here:
        addProviderJLayeredPane.setVisible(true);
          boolean flag = false;
        for(Enterprise e : enterpriseDirectory.getEnterpriseList()){
            if(e instanceof ProviderEnterprise){
                flag = true;
                JOptionPane.showMessageDialog(null, "A State Can Have Only One Provider!");
                addProviderJLayeredPane.setVisible(false);
                
            }
        }
        
        if(flag == false){           
         //   viewSiteJLayeredPane.setVisible(false);
            addProviderJLayeredPane.setVisible(true);
        }
        
    }//GEN-LAST:event_addProviderJButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void providerNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_providerNameJTextFieldActionPerformed

    private void addProviderJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProviderJButton1ActionPerformed
        // TODO add your handling code here:
        addProviderJLayeredPane.setVisible(false);
        String name = providerNameJTextField.getText().trim();
        
        if(!name.isEmpty()){
            Enterprise enterprise = enterpriseDirectory.createAndAddEnterprise(name, EnterpriseType.Provider);
            ProviderEnterprise ent = (ProviderEnterprise) enterprise;
            ent.setStateName(pHDEnterprise.getStateName());
        }else{
            JOptionPane.showMessageDialog(null, "Enter A Name For The Provider Enterprise!");
        }
        populateTable();
    }//GEN-LAST:event_addProviderJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProviderJButton;
    private javax.swing.JButton addProviderJButton1;
    private javax.swing.JLayeredPane addProviderJLayeredPane;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField enterpriseTypeJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable providerJTable;
    private javax.swing.JTextField providerNameJTextField;
    // End of variables declaration//GEN-END:variables
}
