/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdmin;

import business.Disease.Disease;
import business.Disease.DiseaseDirectory;
import business.EcoSystem;

import business.Vaccine.VaccineType;
import business.Vaccine.VaccineTypeDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccineJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private VaccineTypeDirectory vaccineTypeDirectory;
    private DiseaseDirectory diseaseDirectory;
    public ManageVaccineJPanel(JPanel userProcessContainer,EcoSystem ecoSystem ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.vaccineTypeDirectory = ecoSystem.getVaccineDirectory();
        this.diseaseDirectory = ecoSystem.getDiseaseDirectory();
        populateVaccineTable();
        populateComboBox();
        addVaccineJLayeredPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageFunding = new javax.swing.JButton();
        viewStateFundedJButton = new javax.swing.JButton();
        btnStopProd = new javax.swing.JButton();
        btnStrtProd = new javax.swing.JButton();
        AddTypeJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        vaccineJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        addVaccineJLayeredPane = new javax.swing.JLayeredPane();
        txtVaccineType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboFunding = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        CreateJButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboProduction = new javax.swing.JComboBox();
        comboDisease = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Vaccine List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 35, 172, -1));

        btnManageFunding.setText("Change Funding Status");
        btnManageFunding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFundingActionPerformed(evt);
            }
        });
        add(btnManageFunding, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 200, -1));

        viewStateFundedJButton.setText("View State Funded Vaccines");
        viewStateFundedJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStateFundedJButtonActionPerformed(evt);
            }
        });
        add(viewStateFundedJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        btnStopProd.setText("Stop Production");
        btnStopProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopProdActionPerformed(evt);
            }
        });
        add(btnStopProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 170, -1));

        btnStrtProd.setText("Start Production");
        btnStrtProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStrtProdActionPerformed(evt);
            }
        });
        add(btnStrtProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 262, 166, -1));

        AddTypeJButton.setText("Add New Vaccine Type");
        AddTypeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTypeJButtonActionPerformed(evt);
            }
        });
        add(AddTypeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        vaccineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Vaccine Type", "Production Status", "Disease", "Funding"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(vaccineJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 126, 710, 110));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 35, -1, -1));

        addVaccineJLayeredPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addVaccineJLayeredPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addVaccineJLayeredPane.add(txtVaccineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 82, 160, 30));

        jLabel3.setText("Vaccine Type");
        addVaccineJLayeredPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel5.setText("Disease");
        addVaccineJLayeredPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 60, -1));

        comboFunding.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addVaccineJLayeredPane.add(comboFunding, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 160, -1));

        jLabel6.setText("Production");
        addVaccineJLayeredPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        CreateJButton.setText("Create");
        CreateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateJButtonActionPerformed(evt);
            }
        });
        addVaccineJLayeredPane.add(CreateJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Add A New Vaccine");
        addVaccineJLayeredPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel7.setText("Funding");
        addVaccineJLayeredPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        comboProduction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addVaccineJLayeredPane.add(comboProduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 160, 30));

        comboDisease.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiseaseActionPerformed(evt);
            }
        });
        addVaccineJLayeredPane.add(comboDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 122, 160, 30));

        add(addVaccineJLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 374, 417, 363));
    }// </editor-fold>//GEN-END:initComponents

    public void populateVaccineTable()
    {
    
       DefaultTableModel dtm = (DefaultTableModel) vaccineJTable.getModel();
        dtm.setRowCount(0);
        
        for(VaccineType vt : vaccineTypeDirectory.getVaccineList()){
            Object[] row = new Object[5];
            row[0] = vt.getVaccid();
            row[1] = vt;
            row[2] = vt.getStatus();
            row[3] = vt.getDisease().getDiseaseName();
            row[4] = vt.getFundingInfo();
            dtm.addRow(row);
        }
    
    }
    
    private void populateComboBox()
    {
        comboDisease.removeAllItems();
        comboFunding.removeAllItems();
        comboProduction.removeAllItems();
        
         for(Disease d : diseaseDirectory.getDiseaseList()){
            comboDisease.addItem(d);
        }
        
        comboFunding.addItem(VaccineType.FEDERALLYFUNDED);
        comboFunding.addItem(VaccineType.NONFUNDED);
        
        comboProduction.addItem(VaccineType.ACTIVE);
        comboProduction.addItem(VaccineType.DEACTIVE);
    
    }
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewStateFundedJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStateFundedJButtonActionPerformed
        // TODO add your handling code here:
        ViewStateFundedVaccineJPanel vsfvjp = new ViewStateFundedVaccineJPanel(userProcessContainer,vaccineTypeDirectory);
        userProcessContainer.add("ViewStateFundedVaccineJPanel", vsfvjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewStateFundedJButtonActionPerformed

    private void AddTypeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTypeJButtonActionPerformed
        // TODO add your handling code here:
        
        if(diseaseDirectory.getDiseaseList().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Enter a disease first before adding a vaccine");
            return;
        
        }
         addVaccineJLayeredPane.setVisible(true);
         
         
        
    }//GEN-LAST:event_AddTypeJButtonActionPerformed

    private void btnManageFundingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFundingActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = vaccineJTable.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
            VaccineType vt = (VaccineType)vaccineJTable.getValueAt(selectedRow, 1);
            if(vt.getFundingInfo().equals(VaccineType.NONFUNDED)){
                vt.setFundingInfo(VaccineType.FEDERALLYFUNDED);
            }else{
                vt.setFundingInfo(VaccineType.NONFUNDED);
            
        }
        populateVaccineTable();
        
    }//GEN-LAST:event_btnManageFundingActionPerformed

    private void btnStopProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopProdActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        int selectedRow = vaccineJTable.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        else{
            VaccineType vt = (VaccineType)vaccineJTable.getValueAt(selectedRow, 1);
            vt.setStatus(VaccineType.DEACTIVE);
            populateVaccineTable();
        }
    }//GEN-LAST:event_btnStopProdActionPerformed

    private void btnStrtProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStrtProdActionPerformed
        // TODO add your handling code here:
         int selectedRow = vaccineJTable.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
            VaccineType vt = (VaccineType)vaccineJTable.getValueAt(selectedRow, 1);
            vt.setStatus(VaccineType.ACTIVE);
            populateVaccineTable();
        
        
    }//GEN-LAST:event_btnStrtProdActionPerformed

    private void CreateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateJButtonActionPerformed
        // TODO add your handling code here:

        String name = txtVaccineType.getText().trim();
        Disease disease = (Disease)comboDisease.getSelectedItem();
        String funding = (String)comboFunding.getSelectedItem();
        String prod = (String) comboProduction.getSelectedItem();

        if(!name.isEmpty()){
            VaccineType vaccType = vaccineTypeDirectory.createAndAddVaccine();
            vaccType.setVaccineTypeName(name);
            vaccType.setFundingInfo(funding);
            vaccType.setDisease(disease);
            vaccType.setStatus(prod);
            addVaccineJLayeredPane.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "Please Enter A Name for The Vaccine Type!");
        }
        populateVaccineTable();
        txtVaccineType.setText("");
    }//GEN-LAST:event_CreateJButtonActionPerformed

    private void comboDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDiseaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTypeJButton;
    private javax.swing.JButton CreateJButton;
    private javax.swing.JLayeredPane addVaccineJLayeredPane;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnManageFunding;
    private javax.swing.JButton btnStopProd;
    private javax.swing.JButton btnStrtProd;
    private javax.swing.JComboBox comboDisease;
    private javax.swing.JComboBox comboFunding;
    private javax.swing.JComboBox comboProduction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtVaccineType;
    private javax.swing.JTable vaccineJTable;
    private javax.swing.JButton viewStateFundedJButton;
    // End of variables declaration//GEN-END:variables
}
