/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdmin;

import business.Distributor.Warehouse;
import business.EcoSystem;
import business.Enterprise.DistributorEnterprise;
import business.Enterprise.Enterprise;
import business.Enterprise.EnterpriseDirectory;
import business.Role.Role;
import business.UserAccount.UserAccount;
import business.Vaccine.Batch;
import business.Vaccine.Vaccine;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageDistributorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDistributorJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private EnterpriseDirectory enterpriseDirectory;
    public ManageDistributorJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterpriseDirectory = system.getEnterpriseDirectory();
        populateDistributorTable();
        populateRegionComboBox();
    }
    
   private void populateDistributorTable()
   {
   
       if(!enterpriseDirectory.getEnterpriseList().isEmpty())
       {
       
           for(Enterprise e: enterpriseDirectory.getEnterpriseList())
           {
              if(e.getEnterpriseType().equals(Enterprise.EnterpriseType.Distributor))
              {
              
                  txtName.setText(e.getName());
                  for(UserAccount ua : e.getUserAccountDirectory().getUserAccountList())
                  {
                  
                      if(ua.getRole().getRoleName().equalsIgnoreCase(Role.RoleType.DistributorAdminRole.getValue()))
                      {
                      
                      txtAdmin.setText(ua.getPerson().getFirstName()+" "+ua.getPerson().getLastName());
                      
                      }
                  
                  }
              
              }
              
           }
       
       }
   
   
   }
   
   private void populateRegionComboBox()
   {
   
       regionJComboBox.removeAllItems();
       
       for(Enterprise e : enterpriseDirectory.getEnterpriseList())
       {
           if(e.getEnterpriseType().equals(Enterprise.EnterpriseType.Distributor))
           {
           
               DistributorEnterprise distributorEnterprise = (DistributorEnterprise) e;
               
               for(Warehouse w : distributorEnterprise.getWarehouseList())
               {
                   regionJComboBox.addItem(w.getWarehouseRegion());
                   
               }
               
           
           }

       }
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAdmin = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regionJComboBox = new javax.swing.JComboBox();
        goJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        distributorJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Distributor Inventory");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jLabel5.setText("Region");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        txtAdmin.setEditable(false);
        add(txtAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 105, 110, -1));

        txtName.setEditable(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 70, 110, -1));

        jLabel3.setText("Admin");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 108, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Distributor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 30, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 73, -1, -1));

        regionJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        regionJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionJComboBoxActionPerformed(evt);
            }
        });
        add(regionJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 80, -1));

        goJButton.setText("Go!");
        goJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goJButtonActionPerformed(evt);
            }
        });
        add(goJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        distributorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vaccine Type", "Vaccine Name", "Manufacture Date", "Expiry Date", "Batch Number", "Quantity", "Status", "Funding"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(distributorJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 242, 1050, 177));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 34, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void goJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goJButtonActionPerformed
        // TODO add your handling code here:
        
       String region = (String) regionJComboBox.getSelectedItem();
       for(Enterprise e : enterpriseDirectory.getEnterpriseList())
       {
           if(e.getEnterpriseType().equals(Enterprise.EnterpriseType.Distributor))
           {
           
               DistributorEnterprise distributorEnterprise = (DistributorEnterprise) e;
               
               if(!distributorEnterprise.getWarehouseList().isEmpty())
               {
               for(Warehouse w : distributorEnterprise.getWarehouseList())
               {
                   if(w.getWarehouseRegion().equals(region))
                   {
                   
                       DefaultTableModel model = (DefaultTableModel) distributorJTable.getModel();
                       model.setRowCount(0);
                       for(Batch b : w.getBatchDirectory().getBatchList())
                       {
                             Object [] row = new Object[8];
                             for(Vaccine v : b.getVaccineList())
                             {
                             
                                 row[0] = v.getVaccineType().getVaccineTypeName();
                                 row[1] = v.getVaccineName();
                                 row[2] = v.getManufacturedDate();
                                 row[3] = v.getExpireDate();
                                 row[4] = v.getVaccineBatchNo();
                               
                                 row[7] = v.getVaccineType().getFundingInfo();
                                 break;
                             }
                             
                              row[5] = b.getTotalQuantity();
                                row[6] = b.getDistributorInventoryStatus();
                              model.addRow(row);
                             
                       }
                   }
                   
                   
               }
               }
               else
                   {
                       JOptionPane.showMessageDialog(null, "No Distributor warehouse region added yet!");
                   
                   }
               
           
           }

       }
    }//GEN-LAST:event_goJButtonActionPerformed

    private void regionJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable distributorJTable;
    private javax.swing.JButton goJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox regionJComboBox;
    private javax.swing.JTextField txtAdmin;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
