/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.SystemAdmin;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.ManufacturerEnterprise;
import business.Network.StateNetwork;
import business.Vaccine.Batch;
import business.Vaccine.Vaccine;
import business.Vaccine.VaccineType;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Abhishek
 */
public class StateVaccineAllocationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StateVaccineAllocationJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
   
            
    public StateVaccineAllocationJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system =system;
        manucomboBox();
    }
    
    private void manucomboBox()
    {
        manuNameJCombo.removeAllItems();
         for(Enterprise e : system.getEnterpriseDirectory().getEnterpriseList())
        {
            
            if(e.getEnterpriseType().equals(Enterprise.EnterpriseType.Manufacturer))
            {
                manuNameJCombo.addItem(e);
            
            }
                    
        }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manuNameJCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        currInventoryJTable = new javax.swing.JTable();
        viewStateAllocationJButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        vaccineTypeJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vaccineNameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stateDistributionJTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manuNameJCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        manuNameJCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuNameJComboActionPerformed(evt);
            }
        });
        add(manuNameJCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 84, -1, -1));

        jLabel3.setText("Manufacturer Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 88, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage State Vaccine Allocation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 29, -1, -1));

        currInventoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaccine Type", "Vaccine Name", "Batch Available", "Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(currInventoryJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 142, 691, 146));

        viewStateAllocationJButton.setText("View State Allocation");
        viewStateAllocationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStateAllocationJButtonActionPerformed(evt);
            }
        });
        add(viewStateAllocationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 330, -1, -1));

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vaccineTypeJTextField.setEditable(false);
        vaccineTypeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineTypeJTextFieldActionPerformed(evt);
            }
        });
        jLayeredPane1.add(vaccineTypeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 86, 166, -1));

        jLabel2.setText("Vaccine Name :");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 92, -1, -1));

        vaccineNameJTextField.setEditable(false);
        jLayeredPane1.add(vaccineNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 86, 166, -1));

        jLabel4.setText("Vaccine Type :");
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 89, -1, -1));

        stateDistributionJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "State Name", "Population(%)", "No Of VaccineAllocated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(stateDistributionJTable);

        jLayeredPane1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 770, 150));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("State Division Per Vaccine");
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 22, -1, -1));

        add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 381, 843, 392));
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void manuNameJComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuNameJComboActionPerformed
        // TODO add your handling code here:
      
        ManufacturerEnterprise me = (ManufacturerEnterprise) manuNameJCombo.getSelectedItem();
       
        DefaultTableModel model = (DefaultTableModel) currInventoryJTable.getModel();
        ArrayList<Vaccine> vaccineList = new ArrayList<>();
        
        model.setRowCount(0);
        if(me!=null)
        {
              for(VaccineType type : system.getVaccineDirectory().getVaccineList())
            {
            
             for(Batch b : me.getBatchDirectory().getBatchList())
             {        

        
            if(b.getManufacturerInventoryStatus().equalsIgnoreCase(b.INSTOCK))
            {
           
              
                for(Vaccine v : b.getVaccineList())
                    {
                        if(v.getVaccineType().equals(type))
                        {
                        boolean flag = checkExisting(v, vaccineList);
                        if(flag == false)
                        {
                            Object[] row = new Object[5];
                            row[0] = v.getVaccineType().getVaccineTypeName();
                            row[1] = v;
                            row[2] = v.getTotalNumber();
                            row[3] = v.getvPrice();
                            row[4] = b.getManufacturerInventoryStatus();
                            model.addRow(row);
                            vaccineList.add(v);
                            break;
                           
                        }
                        }
                    
                    }

                
                }
             }
                
           }
         }
       

        

    }//GEN-LAST:event_manuNameJComboActionPerformed

      public boolean  checkExisting(Vaccine vName, ArrayList<Vaccine> vList)
    {
    
        if(!vList.isEmpty())
        {
            for(Vaccine v : vList)
            {
                if(v.getVaccineName().equals(vName.getVaccineName()) && v.getVaccineType().getVaccineTypeName().equals(vName.getVaccineType().getVaccineTypeName()))
                {
                
                    return true;
                
                }
            
            }
        
        }
        return false;
    }
    
  
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void viewStateAllocationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStateAllocationJButtonActionPerformed
        // TODO add your handling code here:
        int rowSelected = currInventoryJTable.getSelectedRow();
        
        if(rowSelected<0)
        {
            JOptionPane.showMessageDialog(null, "No row selected");
            return;
        }
        
        Vaccine vac = (Vaccine) currInventoryJTable.getValueAt(rowSelected, 1);
        vaccineNameJTextField.setText(vac.getVaccineName());
        vaccineTypeJTextField.setText(vac.getVaccineType().getVaccineTypeName());
        
        DefaultTableModel model = (DefaultTableModel) stateDistributionJTable.getModel();
        model.setRowCount(0);
        
        
        for(StateNetwork sn : system.getStateNetworkDirectory().getStateNetwork())
        {
            Object[] row = new Object[3];
            row[0] = sn.getState().getName();
            row[1] = system.totalPercentage(system.totalPopulation(), sn.getState().getName());
            
            int percentage  = (int)(system.totalPercentage(system.totalPopulation(), sn.getState().getName()));
            
            int vacAllocationNo = (vac.getTotalNumber()*percentage)/100;
            row[2] = vacAllocationNo;
            model.addRow(row);
        
        }
       
        
        
    }//GEN-LAST:event_viewStateAllocationJButtonActionPerformed

    private void vaccineTypeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineTypeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineTypeJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTable currInventoryJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox manuNameJCombo;
    private javax.swing.JTable stateDistributionJTable;
    private javax.swing.JTextField vaccineNameJTextField;
    private javax.swing.JTextField vaccineTypeJTextField;
    private javax.swing.JButton viewStateAllocationJButton;
    // End of variables declaration//GEN-END:variables
}
