/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Manufacturer;

import business.EcoSystem;
import business.Enterprise.ManufacturerEnterprise;
import business.Vaccine.Batch;
import business.Vaccine.BatchDirectory;
import business.Vaccine.VaccineType;
import business.Vaccine.VaccineTypeDirectory;
import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class AddVaccineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddVaccineJPanel
     */
    private JPanel userProcessContainer;
    private BatchDirectory batchDirectory;
    private ManufacturerEnterprise manufacturerEnterprise;
    private VaccineTypeDirectory typeDirectory;
    private EcoSystem system;
    
    public AddVaccineJPanel(JPanel userProcessContainer, ManufacturerEnterprise manufacturerEnterprise,VaccineTypeDirectory typeDirectory,EcoSystem system ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.manufacturerEnterprise = manufacturerEnterprise;
        this.typeDirectory = typeDirectory;
        this.system = system;
        this.batchDirectory = manufacturerEnterprise.getBatchDirectory();
        Calendar c = Calendar.getInstance();
        manufacturedDateJTextField.setText(c.getTime().toString());
        quantityJTextField.setText("20");
        populateVaccineTypeCombo();
    }
    
    private void populateVaccineTypeCombo()
    {
    
        vaccineTypeJComboBox.removeAllItems();
        
        for(VaccineType type : typeDirectory.getVaccineList())
        {
        
            if(type.getStatus().equals(VaccineType.ACTIVE))
            {
            
                vaccineTypeJComboBox.addItem(type);
            
            }
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        manufacturedDateJTextField = new javax.swing.JTextField();
        priceJTextField = new javax.swing.JTextField();
        quantityJTextField = new javax.swing.JTextField();
        batchJSpinner = new javax.swing.JSpinner();
        vaccineTypeJComboBox = new javax.swing.JComboBox();
        expiryDateJDateChooser = new com.toedter.calendar.JDateChooser();
        vaccineNameJTextField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Add Vaccine");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel2.setText("Vaccine Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 92, -1, -1));

        jLabel3.setText("Vaccine Type :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 136, -1, -1));

        jLabel4.setText("Manufactured Date :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 182, -1, -1));

        jLabel5.setText("Exipiry Date :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel6.setText("Price :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 273, -1, -1));

        jLabel7.setText("No of Batchs :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 313, -1, -1));

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 120, 40));

        jLabel8.setText("Batch Quantity :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 353, -1, -1));

        manufacturedDateJTextField.setEnabled(false);
        manufacturedDateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturedDateJTextFieldActionPerformed(evt);
            }
        });
        add(manufacturedDateJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 176, 210, -1));

        priceJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceJTextFieldActionPerformed(evt);
            }
        });
        add(priceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 270, 210, -1));

        quantityJTextField.setEnabled(false);
        quantityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityJTextFieldActionPerformed(evt);
            }
        });
        add(quantityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 350, 210, -1));
        add(batchJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 310, 210, -1));

        vaccineTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(vaccineTypeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 133, 210, -1));
        add(expiryDateJDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 224, 210, -1));

        vaccineNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineNameJTextFieldActionPerformed(evt);
            }
        });
        add(vaccineNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 89, 210, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manufacturedDateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturedDateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturedDateJTextFieldActionPerformed

    private void priceJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceJTextFieldActionPerformed

    private void quantityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityJTextFieldActionPerformed

    private void vaccineNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccineNameJTextFieldActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
       if(userProcessContainer.getComponent(userProcessContainer.getComponentCount()-1) instanceof ManageVaccineProductionJPanel)
        {
            ManageVaccineProductionJPanel mvpjp = (ManageVaccineProductionJPanel)userProcessContainer.getComponent(userProcessContainer.getComponentCount()-1);
            mvpjp.populateTable();
            
        }
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        
        
        try{
            String name = vaccineNameJTextField.getText().trim();
        float price = Float.parseFloat(priceJTextField.getText());
        int noOfBatch = (int) batchJSpinner.getValue();
        Date expiryDate = expiryDateJDateChooser.getDate();
        VaccineType vaccType = (VaccineType) vaccineTypeJComboBox.getSelectedItem();
        Calendar c = Calendar.getInstance();
            if(!name.isEmpty())
        {
            if(expiryDate.compareTo(c.getTime())>0)
            {
                if(noOfBatch>0)
                {
                    for(int i=0;i<noOfBatch;i++)
                    {
                     //batchDirectory.createAndAddBatch(vaccType, name, price, c.getTime(), expiryDate,noOfBatch);
                         Batch batch = batchDirectory.createAndAddBatch(vaccType, name, price, c.getTime() ,expiryDate,noOfBatch,name);
                            system.getBatchDirectory().getBatchList().add(batch);
                    }
                
                }
                else
                {
                     JOptionPane.showMessageDialog(null, "enter a valid Batch Quantity");
                
                }
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "enter a valid expiry date");
            
            }
        
             }
        else{
            JOptionPane.showMessageDialog(null, "enter a vaccine name");
        
         }
        }
        catch(NumberFormatException nfe)
        {
        
            JOptionPane.showMessageDialog(null, "Enter a valid price");
        
        }
            vaccineNameJTextField.setText("");
            priceJTextField.setText("");
        
    }//GEN-LAST:event_addJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JSpinner batchJSpinner;
    private javax.swing.JButton btnBack;
    private com.toedter.calendar.JDateChooser expiryDateJDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField manufacturedDateJTextField;
    private javax.swing.JTextField priceJTextField;
    private javax.swing.JTextField quantityJTextField;
    private javax.swing.JTextField vaccineNameJTextField;
    private javax.swing.JComboBox vaccineTypeJComboBox;
    // End of variables declaration//GEN-END:variables
}
