/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Manufacturer;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Enterprise.ManufacturerEnterprise;
import business.UserAccount.UserAccount;
import business.Vaccine.VaccineTypeDirectory;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class ManufacturerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManufacturerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private ManufacturerEnterprise manufacturerEnterprise;
    private VaccineTypeDirectory vaccineTypeDirectory;
    private UserAccount userAccount;
    
    public ManufacturerWorkAreaJPanel(JPanel userProcessContainer,EcoSystem system, Enterprise enterprise,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.manufacturerEnterprise = (ManufacturerEnterprise)enterprise;
        this.vaccineTypeDirectory = system.getVaccineDirectory();
        this.userAccount = userAccount;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enrollRequestJButton = new javax.swing.JButton();
        manageVaccineProductionJButton = new javax.swing.JButton();
        managePaymentJButton = new javax.swing.JButton();
        manageOrdersJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel1.setText("Manufacturer Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 352, -1));

        enrollRequestJButton.setText("Enroll Requests");
        enrollRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollRequestJButtonActionPerformed(evt);
            }
        });
        add(enrollRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 190, -1));

        manageVaccineProductionJButton.setText("Manage Vaccine Production");
        manageVaccineProductionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVaccineProductionJButtonActionPerformed(evt);
            }
        });
        add(manageVaccineProductionJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        managePaymentJButton.setText("Manage Payment");
        managePaymentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePaymentJButtonActionPerformed(evt);
            }
        });
        add(managePaymentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 189, -1));

        manageOrdersJButton.setText("Manage Orders");
        manageOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersJButtonActionPerformed(evt);
            }
        });
        add(manageOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 189, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void managePaymentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePaymentJButtonActionPerformed
        // TODO add your handling code here:
        ManageManufacturerPaymentAccountJPanel mmpajp = new ManageManufacturerPaymentAccountJPanel(userProcessContainer, system,userAccount);
        userProcessContainer.add("ManageManufacturerPaymentAccountJPanel", mmpajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePaymentJButtonActionPerformed

    private void manageVaccineProductionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVaccineProductionJButtonActionPerformed
        // TODO add your handling code here:
        if(!userAccount.getWorkQueue().getWorkRequestList().isEmpty())
        {
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList())
        {
        
            if(request.getMessage().equals("Distributor Approval Pending"))
            {
                JOptionPane.showMessageDialog(null, "You cant produce vaccine until your enrollement is accepted by the distributor");
            }
            else if(request.getMessage().equals("Declined!"))
            {
                JOptionPane.showMessageDialog(null, "You cant produce vaccine as your enrollment is declined by distributor, you can raise another enrollment");
            }
            else
            {
                
                  ManageVaccineProductionJPanel mvpjp = new ManageVaccineProductionJPanel(userProcessContainer, manufacturerEnterprise, vaccineTypeDirectory,system);
                userProcessContainer.add("ManageNetworkJPanel", mvpjp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
               layout.next(userProcessContainer);
            
            }
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "You cant produce vaccine until you are registered with the distributor");
        
        }
        
    }//GEN-LAST:event_manageVaccineProductionJButtonActionPerformed

    private void enrollRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollRequestJButtonActionPerformed
        // TODO add your handling code here:
        
        
         ManageManufacturerEnrollmentsJPanel mmejp = new ManageManufacturerEnrollmentsJPanel(userProcessContainer,system,manufacturerEnterprise);
        userProcessContainer.add("ManageNetworkJPanel", mmejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_enrollRequestJButtonActionPerformed

    private void manageOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersJButtonActionPerformed
        // TODO add your handling code here:
        ManageDistributorOrderJPanel mdojp = new ManageDistributorOrderJPanel(userProcessContainer,system,userAccount,manufacturerEnterprise);
        userProcessContainer.add("ManageDistributorOrderJPanel", mdojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrdersJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enrollRequestJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageOrdersJButton;
    private javax.swing.JButton managePaymentJButton;
    private javax.swing.JButton manageVaccineProductionJButton;
    // End of variables declaration//GEN-END:variables
}
